### ISSUE TITLE
Bump up versions?

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.app.robotframework#38]
Some of my tests started failing today and I saw there are new versions of some dependencies:

* [plone.app.robotframework](https://pypi.python.org/pypi/plone.app.robotframework)
* [robotframework](https://pypi.python.org/pypi/robotframework)
* [robotframework-selenium2library](https://pypi.python.org/pypi/robotframework-selenium2library)

Do we need to update something?

**Comment by datakurre** [comment]
@hvelarde Strange. I'm not aware of any such changes.

**Comment by hvelarde** [comment]
see https://travis-ci.org/collective/collective.nitf/jobs/60413456#L3177 as am example; this was passing before.

**Comment by datakurre** [comment]
Of course, it could be an issue with new Firefox and Selenium as usual, but that leaves us broken until new version of Python Selenium gets released :/

**Comment by polyester** [comment]
Could we also update dependency Pygments to 2.0.2 ? That allows the docs.plone.org to move to Sphinx 1.3.1, which is *much* faster and nicer. When 'manually' testing building the Plone docs, everything seems to work, robots run and screenshots are taken. But I'm not 100% sure how to test it against all usecases.

**Comment by datakurre** [comment]
@polyester Thanks for pointing that. Pygments is pinned only, because it started to include robotframework syntax in >= 1.6

@hvelarde According to https://github.com/SeleniumHQ/selenium/blob/master/py/CHANGES the currently pinned Selenium 2.45.0 is quarenteed to work only up to Firefox 35, so there may really be issues, yet I cannot see anything related in Selenium issues at glance.

But you could try out, if our tests pass with phantomjs. (Set env ROBOT_BROWSER=phantomjs)
